### ISSUE TITLE
RemoteStream not show in local device!

### ISSUE THREAD

**Issue by chep267** [DipanshKhandelwal/react-native-webrtc-firebase#9]
Today i got this issues, but not error.
I use your examp, the same goes! 
Help me, please!

**Comment by DipanshKhandelwal** [comment]
it will helpful if you can share more details about it.

**Comment by chep267** [comment]
Hi, bro!
Thank yoy very much!

Em đã biết được chỗ cần fix rồi ạ, em cảm ơn anh rất nhiều vì đã giải đáp,
viết hướng dẫn giúp em!
Em chúc anh mạnh khỏe và làm việc hiệu quả ạ!!


Vào 19:13, Th 6, 29 thg 1, 2021 Dipansh Khandelwal <notifications@github.com>
đã viết:

**Comment by rajeshbethuhyd** [comment]
Hi Bro
I faced the same issue 
both call screen and join screen on two devices are showing their local stream only even after connecting.
please help.
thank you

**Comment by rajeshbethuhyd** [comment]
> 

Bro Please help me if you have already fixed this issue.
Thank you

**Comment by ghost** [comment]
Same kind of issue i m having. it's giving me an error on clicking the start stream button and sometimes just nothing happens on click of it.
it's only showing local stream on both devices

Error!
Possible Unhandled Promise Rejection (id: 1):
TypeError: undefined is not a function
TypeError: undefined is not a function
    at ?anon_0_ (http://192.168.1.4:8081/src/screens/CallScreen.bundle?platform=android&app=com.webrtc&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:86:26)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:21648:26)
    at _next (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:21667:29)
    at anonymous (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:21672:14)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/3f4v354d/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/3f4v354d/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/3f4v354d/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:21664:25)
    at apply (native)
    at startCall (http://192.168.1.4:8081/src/screens/CallScreen.bundle?platform=android&app=com.webrtc&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:136:27)
    at onPress (http://192.168.1.4:8081/src/screens/CallScreen.bundle?platform=android&app=com.webrtc&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:177:31)
    at _performTransitionSideEffects (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:77492:22)
    at _receiveSignal (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:77446:45)
    at onResponderRelease (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:77311:34)
    at apply (native)
    at invokeGuardedCallbackProd (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:2947:21)
    at apply (native)
    at invokeGuardedCallback (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:3047:42)
    at apply (native)
    at invokeGuardedCallbackAndCatchFirstError (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:3051:36)
    at executeDispatch (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:3118:48)
    at executeDispatchesInOrder (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:3137:26)
    at executeDispatchesAndRelease (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:4317:35)
    at executeDispatchesAndReleaseTopLevel (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:4324:43)
    at forEach (native)
    at forEachAccumulated (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:3598:22)
    at runEventsInBatch (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:4336:27)
    at runExtractedPluginEventsInBatch (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:4402:25)
    at anonymous (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:4382:42)
    at batchedUpdates$1 (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:15603:20)
    at batchedUpdates (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:4304:36)
    at _receiveRootNodeIDEvent (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:4381:23)
    at receiveTouches (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:4429:34)
    at apply (native)
    at __callFunction (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:2471:36)
    at anonymous (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:2221:31)
    at __guard (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:2419:15)
    at callFunctionReturnFlushedQueue (http://192.168.1.4:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtc&modulesOnly=false&runModule=true:2220:21)
